import type { FallbackEntry } from '../lib/types'
import { StatTile } from './charts'
import { EmptyState } from './EmptyState'

export function AiFallback({ entries }: { entries: FallbackEntry[] }) {
  return (
    <div className="panel">
      <h1>AI Fallback</h1>
      <p className="panel__intro">
        Cowrie's fake shell only has scripted responses for commands its developers implemented.
        Anything else used to be a flat "command not found" - an easy tell for a careful bot. Now
        those gaps get a plausible response generated by a small open model (Qwen2.5-Coder-3B via
        Hugging Face's free tier), cached so each distinct command is only ever generated once,
        shared across every attacker.
      </p>

      <section className="kpi-row" style={{ marginBottom: '28px' }}>
        <StatTile
          label="Commands the honeypot has learned to fake"
          value={entries.length}
          accent="var(--cat-5)"
          icon={
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6">
              <path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1" />
              <circle cx="12" cy="12" r="3.5" />
            </svg>
          }
        />
      </section>

      {entries.length === 0 ? (
        <EmptyState message="No AI-generated responses yet - check back after an attacker runs something Cowrie doesn't already know." />
      ) : (
        <div className="fallback-list">
          {entries.map((entry) => (
            <div className="fallback-entry" key={entry.command}>
              <div className="fallback-entry__head">
                <span className="fallback-entry__command">$ {entry.command}</span>
                <span
                  className={`fallback-entry__badge ${
                    entry.exit_code === 0
                      ? 'fallback-entry__badge--ok'
                      : 'fallback-entry__badge--fail'
                  }`}
                >
                  exit {entry.exit_code}
                </span>
              </div>
              <pre className="fallback-entry__output">{entry.output}</pre>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
